---
- name: Create web directory
  file:
    path: "/home/ubuntu/backend-app"
    state: directory
    # mode: '0755'


- name: Extract zipped artifact
  # shell: tar xvzf:
  become: true
  unarchive:
    # remote_src: yes 
    src: .circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: Install npm dependencies
  shell: |
    cd /home/ubuntu/backend-app
    npm i

- name: Start app with pm2
  shell: |
    cd /home/ubuntu/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "Configuring pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save

# VS Code Extension Version: 1.5.1